---
image: docker:19.03.0

stages:
  - build
  - test
  - publish
  - release

variables:
  PANDOC_IMAGE: ${CI_REGISTRY_IMAGE}
  PANDOC_BUILD_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.0-dind

before_script:
  - env
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  - docker info

build_image:
  stage: build
  script:
    - docker build -t ${PANDOC_BUILD_IMAGE} .
    - docker push ${PANDOC_BUILD_IMAGE}
  tags:
    - docker

publish_latest:
  stage: publish
  script:
    - docker pull ${PANDOC_BUILD_IMAGE}
    - push_tag="${PANDOC_IMAGE}:latest"
    - docker tag ${PANDOC_BUILD_IMAGE} ${push_tag}
    - docker push ${push_tag}
  only:
    - master
  tags:
    - docker

release_image:
  stage: release
  script:
    - docker pull ${PANDOC_BUILD_IMAGE}
    - push_tag="${PANDOC_IMAGE}:${CI_COMMIT_TAG#v}"
    - docker tag ${PANDOC_BUILD_IMAGE} ${push_tag}
    - docker push ${push_tag}
  only:
    - tags
  tags:
    - docker

